name: Westchester Veterinary Hospital
favicon: null
layout_spectrum: 0.4334544974844903
typography_spectrum: 0.13573103258386254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2757775557693094
  lightness: 0.20820874301716685
  saturation: 0.03324487362988293
  rhythmicContrast: 0.25986772729083896
purpose: []
